### ISSUE TITLE
Weird State nesting bug

### ISSUE THREAD

**Issue by MoAtefAmer** [treeder/state#2]
Some context, I tried using this repo on a chrome extension. Worked fine however there was a weird bug where when you keep closing and opening the chrome extension the state kept cluttering and nesting objects inside itself taking up space needlessly. I dont fully understand why this behaviour occurs but its something like this:
![image](https://github.com/treeder/state/assets/47057819/a1af9a5d-0575-4ade-8c2e-74bb058b57f3)

Mabye im misusing the repo or setting it wrong, however i cloned the state file locally and when I added this condition to the for loop it fixed it.

So this 
```
  // the alternative way using individual keys
        for (let key in localStorage) {
            if (key.startsWith(State.statePrefix)) {
                let value = localStorage.getItem(key);
                value = JSON.parse(value);
                this.stateMap.set(key.substring(State.statePrefix.length), value);
            }
        }
 ```

instead of this 
```
   for (let key in localStorage) {
            let value = localStorage.getItem(key)
            value = JSON.parse(value)
            this.stateMap.set(key, value)
        }
   ```

This becomes the result and it doesnt do the weird nesting thing after the chrome extension is closed and opened
![image](https://github.com/treeder/state/assets/47057819/e3673fc8-2772-466a-8ca3-9cdc12898ccf)

**Comment by treeder** [comment]
Good catch, just updated it. 

To force an update on the CDN, try this import with 0.0.9.  

import state from 'https://cdn.jsdelivr.net/gh/treeder/state@0.0.9/state.js'

Let me know if it fixes your issue.

**Comment by MoAtefAmer** [comment]
Unfortanetly cant use cdns ( or remote code in general )in chrome extension, google blocks it and considers it a cross site scripting threat.

 will copy the code and try it locally anyway, thanks for the update 👍

**Comment by treeder** [comment]
👍

**Comment by MoAtefAmer** [comment]
Yeah just tried it, this works
